update @ 2024-03-12 16:13:57 UTC
### 3sat

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/connection.py", line 472, in connect
    _match_hostname(cert, self.assert_hostname or server_hostname)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/connection.py", line 545, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/util/ssl_match_hostname.py", line 150, in match_hostname
    raise CertificateError(
urllib3.util.ssl_match_hostname.CertificateError: hostname 'blog.3sat.de' doesn't match either of '*.zdf.de', 'zdf.de'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='blog.3sat.de', port=443): Max retries exceeded with url: /ttx/index.php?p=100_0001&c=0 (Caused by SSLError(CertificateError("hostname 'blog.3sat.de' doesn't match either of '*.zdf.de', 'zdf.de'")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2024/teletext-archive-2024/src/scraper.py", line 186, in get_html
    return self.session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='blog.3sat.de', port=443): Max retries exceeded with url: /ttx/index.php?p=100_0001&c=0 (Caused by SSLError(CertificateError("hostname 'blog.3sat.de' doesn't match either of '*.zdf.de', 'zdf.de'")))
```
### ard

- 282 pages changed
- 23 pages added
- 3 pages removed
- 786 pages unchanged

### ndr

- 348 pages changed
- 14 pages added
- 7 pages removed
- 853 pages unchanged

### ntv

- 696 pages changed
- 3 pages added
- 214 pages unchanged

### sr

- 64 pages changed
- 14 pages added
- 9 pages removed
- 403 pages unchanged

### wdr

- 231 pages changed
- 23 pages added
- 42 pages removed
- 747 pages unchanged

### zdf

- 500 pages changed
- 81 pages added
- 41 pages removed
- 392 pages unchanged

### zdf-info

- 390 pages changed
- 54 pages added
- 32 pages removed
- 160 pages unchanged

### zdf-neo

- 140 pages changed
- 2 pages added
- 49 pages removed
- 140 pages unchanged