update @ 2024-02-15 08:13:36 UTC
### 3sat

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/connection.py", line 472, in connect
    _match_hostname(cert, self.assert_hostname or server_hostname)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/connection.py", line 545, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/util/ssl_match_hostname.py", line 150, in match_hostname
    raise CertificateError(
urllib3.util.ssl_match_hostname.CertificateError: hostname 'blog.3sat.de' doesn't match either of '*.zdf.de', 'zdf.de'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='blog.3sat.de', port=443): Max retries exceeded with url: /ttx/index.php?p=100_0001&c=0 (Caused by SSLError(CertificateError("hostname 'blog.3sat.de' doesn't match either of '*.zdf.de', 'zdf.de'")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2024/teletext-archive-2024/src/scraper.py", line 186, in get_html
    return self.session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='blog.3sat.de', port=443): Max retries exceeded with url: /ttx/index.php?p=100_0001&c=0 (Caused by SSLError(CertificateError("hostname 'blog.3sat.de' doesn't match either of '*.zdf.de', 'zdf.de'")))
```
### ard

- 296 pages changed
- 7 pages added
- 36 pages removed
- 770 pages unchanged

### ndr

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/ssl.py", line 1132, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/connectionpool.py", line 469, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/connectionpool.py", line 358, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.ndr.de', port=443): Read timed out. (read timeout=20)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2024/teletext-archive-2024/src/scraper.py", line 186, in get_html
    return self.session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.ndr.de', port=443): Read timed out. (read timeout=20)
```
### ntv

- 641 pages changed
- 1 pages added
- 12 pages removed
- 265 pages unchanged

### sr

- 97 pages changed
- 5 pages added
- 10 pages removed
- 361 pages unchanged

### wdr

- 254 pages changed
- 19 pages added
- 9 pages removed
- 737 pages unchanged

### zdf

- 490 pages changed
- 55 pages added
- 71 pages removed
- 464 pages unchanged

### zdf-info

- 459 pages changed
- 31 pages added
- 39 pages removed
- 114 pages unchanged

### zdf-neo

- 205 pages changed
- 88 pages added
- 10 pages removed
- 78 pages unchanged