update @ 2024-02-24 16:12:03 UTC
### 3sat

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/connection.py", line 472, in connect
    _match_hostname(cert, self.assert_hostname or server_hostname)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/connection.py", line 545, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/util/ssl_match_hostname.py", line 150, in match_hostname
    raise CertificateError(
urllib3.util.ssl_match_hostname.CertificateError: hostname 'blog.3sat.de' doesn't match either of '*.zdf.de', 'zdf.de'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='blog.3sat.de', port=443): Max retries exceeded with url: /ttx/index.php?p=100_0001&c=0 (Caused by SSLError(CertificateError("hostname 'blog.3sat.de' doesn't match either of '*.zdf.de', 'zdf.de'")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2024/teletext-archive-2024/src/scraper.py", line 186, in get_html
    return self.session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='blog.3sat.de', port=443): Max retries exceeded with url: /ttx/index.php?p=100_0001&c=0 (Caused by SSLError(CertificateError("hostname 'blog.3sat.de' doesn't match either of '*.zdf.de', 'zdf.de'")))
```
### ard

- 316 pages changed
- 36 pages added
- 4 pages removed
- 734 pages unchanged

### ndr

- 366 pages changed
- 10 pages added
- 9 pages removed
- 900 pages unchanged

### ntv

- 289 pages changed
- 1 pages added
- 633 pages unchanged

### sr

- 104 pages changed
- 29 pages added
- 12 pages removed
- 322 pages unchanged

### wdr

- 299 pages changed
- 16 pages added
- 29 pages removed
- 712 pages unchanged

### zdf

- 262 pages changed
- 33 pages added
- 66 pages removed
- 453 pages unchanged

### zdf-info

- 143 pages changed
- 3 pages added
- 31 pages removed
- 242 pages unchanged

### zdf-neo

- 121 pages changed
- 3 pages added
- 51 pages removed
- 157 pages unchanged